### ISSUE TITLE
Can't compile. UMain.dfm corrupt 

### ISSUE THREAD

**Issue by stokie-ant** [mendelgusmao/LCD-Smartie#1]
Error reading LCDSmartieDisplayForm.PixelsPerI: Property PixelsPerI does not exist. 

Using an old UMain.dfm works but There's still a shed load of errors I need to get through

**Comment by mendelgusmao** [comment]
Hi @stokie-ant! This repository is just a very out of date mirror! Please refer to http://lcdsmartie.org/phpBB3/ or http://lcdsmartie.sourceforge.net/ for official development support. Thanks!
